/*
 * Automatically generated by jrpcgen 1.0.7 on 10/5/07 11:51 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.jnode.fs.nfs.nfs2.rpc.nfs;

import java.io.IOException;

import org.acplt.oncrpc.OncRpcException;
import org.acplt.oncrpc.XdrAble;
import org.acplt.oncrpc.XdrDecodingStream;
import org.acplt.oncrpc.XdrEncodingStream;

public class Entry implements XdrAble {
    private int fileId;
    private String name;
    private byte[] cookie;
    private Entry nextEntry;

    public Entry() {
    }

    public Entry(XdrDecodingStream xdr) throws OncRpcException, IOException {
        xdrDecode(xdr);
    }


    public void setFileId(int x) {
        this.fileId = x;
    }

    public int getFileId() {
        return this.fileId;
    }

    public void setName(String x) {
        this.name = x;
    }

    public String getName() {
        return this.name;
    }

    public void setCookie(byte[] x) {
        this.cookie = x;
    }

    public byte[] getCookie() {
        return this.cookie;
    }

    public void setNextEntry(Entry x) {
        this.nextEntry = x;
    }

    public Entry getNextEntry() {
        return this.nextEntry;
    }


    public void xdrEncode(XdrEncodingStream xdr) throws OncRpcException, IOException {
        Entry currentEntry = this;
        do {
            xdr.xdrEncodeInt(currentEntry.getFileId());
            xdr.xdrEncodeString(currentEntry.getName());
            xdr.xdrEncodeOpaque(currentEntry.getCookie(), NFS2Client.COOKIE_SIZE);
            currentEntry = currentEntry.getNextEntry();
            xdr.xdrEncodeBoolean(currentEntry != null);
        } while (currentEntry != null);
    }

    public void xdrDecode(XdrDecodingStream xdr) throws OncRpcException, IOException {
        Entry currentEntry = this;
        do {
            currentEntry.setFileId(xdr.xdrDecodeInt());
            currentEntry.setName(xdr.xdrDecodeString());
            currentEntry.setCookie(xdr.xdrDecodeOpaque(NFS2Client.COOKIE_SIZE));
            currentEntry.setNextEntry(xdr.xdrDecodeBoolean() ? new Entry() : null);
            currentEntry = currentEntry.getNextEntry();
        } while (currentEntry != null);
    }

}
// End of Entry.java
