/*
 * Automatically generated by jrpcgen 1.0.7 on 10/5/07 11:51 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.jnode.fs.nfs.nfs2.rpc.nfs;

/**
 * Enumeration (collection of constants).
 */
public interface FileType {

    public static final int NON_FILE = 0;
    public static final int FILE = 1;
    public static final int DIRECTORY = 2;
    public static final int BLOCK_SPECIAL_DEVICE = 3;
    public static final int CHARACTER_SPECIAL_DEVICE = 4;
    public static final int SYMBOLIC_LINK = 5;

}
// End of FileType.java
