/*
 * Automatically generated by jrpcgen 1.0.7 on 10/5/07 11:51 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.jnode.fs.nfs.nfs2.rpc.nfs;

import java.io.IOException;

import org.acplt.oncrpc.OncRpcException;
import org.acplt.oncrpc.XdrAble;
import org.acplt.oncrpc.XdrDecodingStream;
import org.acplt.oncrpc.XdrEncodingStream;

public class FileAttribute implements XdrAble {
    protected int type;
    protected int mode;
    protected int nlink;
    protected int uid;
    protected int gid;
    protected int size;
    protected int blocksize;
    protected int rdev;
    protected int blocks;
    protected int fsid;
    protected int fileid;
    protected Time lastAccessed;
    protected Time lastModified;
    protected Time lastStatusChanged;

    public void setType(int x) {
        this.type = x;
    }

    public int getType() {
        return this.type;
    }

    public void setMode(int x) {
        this.mode = x;
    }

    public int getMode() {
        return this.mode;
    }

    public void setNlink(int x) {
        this.nlink = x;
    }

    public int getNlink() {
        return this.nlink;
    }

    public void setUid(int x) {
        this.uid = x;
    }

    public int getUid() {
        return this.uid;
    }

    public void setGid(int x) {
        this.gid = x;
    }

    public int getGid() {
        return this.gid;
    }

    public void setSize(int x) {
        this.size = x;
    }

    public int getSize() {
        return this.size;
    }

    public void setBlocksize(int x) {
        this.blocksize = x;
    }

    public int getBlocksize() {
        return this.blocksize;
    }

    public void setRdev(int x) {
        this.rdev = x;
    }

    public int getRdev() {
        return this.rdev;
    }

    public void setBlocks(int x) {
        this.blocks = x;
    }

    public int getBlocks() {
        return this.blocks;
    }

    public void setFsid(int x) {
        this.fsid = x;
    }

    public int getFsid() {
        return this.fsid;
    }

    public void setFileid(int x) {
        this.fileid = x;
    }

    public int getFileid() {
        return this.fileid;
    }

    public void setLastAccessed(Time x) {
        this.lastAccessed = x;
    }

    public Time getLastAccessed() {
        return this.lastAccessed;
    }

    public void setLastModified(Time x) {
        this.lastModified = x;
    }

    public Time getLastModified() {
        return this.lastModified;
    }

    public void setLastStatusChanged(Time x) {
        this.lastStatusChanged = x;
    }

    public Time getLastStatusChanged() {
        return this.lastStatusChanged;
    }

    public FileAttribute() {
    }

    public FileAttribute(XdrDecodingStream xdr) throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) throws OncRpcException, IOException {
        xdr.xdrEncodeInt(type);
        xdr.xdrEncodeInt(mode);
        xdr.xdrEncodeInt(nlink);
        xdr.xdrEncodeInt(uid);
        xdr.xdrEncodeInt(gid);
        xdr.xdrEncodeInt(size);
        xdr.xdrEncodeInt(blocksize);
        xdr.xdrEncodeInt(rdev);
        xdr.xdrEncodeInt(blocks);
        xdr.xdrEncodeInt(fsid);
        xdr.xdrEncodeInt(fileid);
        lastAccessed.xdrEncode(xdr);
        lastModified.xdrEncode(xdr);
        lastStatusChanged.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) throws OncRpcException, IOException {
        type = xdr.xdrDecodeInt();
        mode = xdr.xdrDecodeInt();
        nlink = xdr.xdrDecodeInt();
        uid = xdr.xdrDecodeInt();
        gid = xdr.xdrDecodeInt();
        size = xdr.xdrDecodeInt();
        blocksize = xdr.xdrDecodeInt();
        rdev = xdr.xdrDecodeInt();
        blocks = xdr.xdrDecodeInt();
        fsid = xdr.xdrDecodeInt();
        fileid = xdr.xdrDecodeInt();
        lastAccessed = new Time(xdr);
        lastModified = new Time(xdr);
        lastStatusChanged = new Time(xdr);
    }

}
// End of FileAttribute.java
