/*
 * Automatically generated by jrpcgen 1.0.7 on 10/5/07 11:51 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.jnode.fs.nfs.nfs2.rpc.nfs;

import java.io.IOException;

import org.acplt.oncrpc.OncRpcException;
import org.acplt.oncrpc.XdrDecodingStream;

public class ListDirectoryResult extends AbstractResult {

    private Entry entry;
    private boolean eof;

    public ListDirectoryResult() {
    }

    public ListDirectoryResult(XdrDecodingStream xdr) throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void decode(XdrDecodingStream xdr) throws OncRpcException, IOException {

        entry = xdr.xdrDecodeBoolean() ? new Entry(xdr) : null;
        eof = !xdr.xdrDecodeBoolean();

    }

    public Entry getEntry() {
        return entry;
    }

    public boolean isEof() {
        return eof;
    }

}
// End of ReadDirectoryResult.java
