/*
 * Automatically generated by jrpcgen 1.0.7 on 10/5/07 11:51 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.jnode.fs.nfs.nfs2.rpc.nfs;


public class ListDirectoryResult {

    private Entry entry;
    private boolean eof;

    public void setEntry(Entry entry) {
        this.entry = entry;
    }

    public void setEof(boolean eof) {
        this.eof = eof;
    }

    public Entry getEntry() {
        return entry;
    }

    public boolean isEof() {
        return eof;
    }

}
