/*
 * Automatically generated by jrpcgen 1.0.7 on 10/5/07 11:51 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.jnode.fs.nfs.nfs2.rpc.nfs;

import java.io.IOException;

import org.acplt.oncrpc.OncRpcException;
import org.acplt.oncrpc.XdrAble;
import org.acplt.oncrpc.XdrDecodingStream;
import org.acplt.oncrpc.XdrEncodingStream;

public class Time implements XdrAble {
    protected int seconds;
    protected int microSeconds;

    public void setSeconds(int x) {
        this.seconds = x;
    }

    public int getSeconds() {
        return this.seconds;
    }

    public void setMicroSeconds(int x) {
        this.microSeconds = x;
    }

    public int getMicroSeconds() {
        return this.microSeconds;
    }

    public Time() {
    }

    public Time(XdrDecodingStream xdr) throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) throws OncRpcException, IOException {
        xdr.xdrEncodeInt(seconds);
        xdr.xdrEncodeInt(microSeconds);
    }

    public void xdrDecode(XdrDecodingStream xdr) throws OncRpcException, IOException {
        seconds = xdr.xdrDecodeInt();
        microSeconds = xdr.xdrDecodeInt();
    }

}
// End of Time.java
