package org.omg.IOP;


/**
* org/omg/IOP/ENCODING_CDR_ENCAPS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Friday, May 25, 2007 3:39:55 o'clock PM GMT-05:00
*/

public interface ENCODING_CDR_ENCAPS
{

  /**
     * The CDR Encapsulation encoding.
     * @see CodecFactory
     */
  public static final short value = (short)(0);
}
