package org.omg.IOP;


/**
* org/omg/IOP/RMICustomMaxStreamFormat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Friday, May 25, 2007 3:39:55 o'clock PM GMT-05:00
*/

public interface RMICustomMaxStreamFormat
{

  /**
       * Identifies a CDR encapsulation of the RMICustomMaxStreamFormat
       * service context which contains a single byte specifying
       * the client's maximum RMI-IIOP stream format version.
       *
       * See Java to IDL ptc/02-01-12 1.4.12.
       */
  public static final int value = (int)(17L);
}
