package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/IIOP_CLEAR_TEXT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Friday, May 25, 2007 4:50:48 o'clock PM EDT
*/

public interface IIOP_CLEAR_TEXT
{

  // to avoid a compilation dependency.
  public static final String value = "IIOP_CLEAR_TEXT";
}
