/*
 * $Id$
 *
 * JNode.org
 * Copyright (C) 2003-2006 JNode.org
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public 
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; If not, write to the Free Software Foundation, Inc., 
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
 
package org.jnode.awt;

import org.jnode.driver.video.HardwareCursor;
import org.jnode.driver.video.HardwareCursorImage;

/**
 * @author Ewout Prangsma (epr@users.sourceforge.net)
 */
public class JNodeCursors {


	private static final String ARROW_IMAGE_16x16 =
	    "BBTTTTTTTTTTTTTT" +
	    "BWBTTTTTTTTTTTTT" +
	    "BWWBTTTTTTTTTTTT" +
	    "BWWWBTTTTTTTTTTT" +
	    "BWWWWBTTTTTTTTTT" +
	    "BWWWWWBTTTTTTTTT" +
	    "BWWWWWWBTTTTTTTT" +
	    "BWWWWWWWBTTTTTTT" +
	    "BWWWWWWWWBTTTTTT" +
	    "BWWWWWWWWWBTTTTT" +
	    "BWWBWWWBBBBBTTTT" +
	    "BWBTBWWBTTTTTTTT" +
	    "BBTTTBWWBTTTTTTT" +
	    "TTTTTTBWWBTTTTTT" +
	    "TTTTTTTBWWBTTTTT" +
	    "TTTTTTTTBBBTTTTT";

    private static final String ARROW_IMAGE_32x32 =
		"BTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"BBTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"BWBTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"BWWBTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"BWWWBTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"BWWWWBTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"BWWWWWBTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"BWWWWWWBTTTTTTTTTTTTTTTTTTTTTTTT" +
		"BWWWWWWWBTTTTTTTTTTTTTTTTTTTTTTT" +
		"BWWWWWWWWBTTTTTTTTTTTTTTTTTTTTTT" +
		"BWWWWWWWWWBTTTTTTTTTTTTTTTTTTTTT" +
		"BWWWWWWWWWWBTTTTTTTTTTTTTTTTTTTT" +
		"BWWWWWWWWWWWBTTTTTTTTTTTTTTTTTTT" +
		"BWWWWWWWWWWWWBTTTTTTTTTTTTTTTTTT" +
		"BWWWWWWWWWWWWWBTTTTTTTTTTTTTTTTT" +
		"BWWWWWWWWWWWWWWBTTTTTTTTTTTTTTTT" +
		"BWWWWWWWWWWWWWWWBTTTTTTTTTTTTTTT" +
		"BWWWWWWWWWWWWWWWWBTTTTTTTTTTTTTT" +
		"BWWWWWWWWWWWWWWWWWBTTTTTTTTTTTTT" +
		"BWWWWWWWWWWWWWWWWWWBTTTTTTTTTTTT" +
		"BWWWWWWWWWWWWWWWWWWWBTTTTTTTTTTT" +
		"BWWWWWWWWWWWWWWWWWWWWBTTTTTTTTTT" +
		"BWWWWWWWWWWWWWWWWWWWWWBTTTTTTTTT" +
		"BWWWWWWBWWWWWWBBBBBBBBBBTTTTTTTT" +
		"BWWWWWBTBWWWWWWBTTTTTTTTTTTTTTTT" +
		"BWWWWBTTTBWWWWWWBTTTTTTTTTTTTTTT" +
		"BWWWBTTTTTBWWWWWWBTTTTTTTTTTTTTT" +
		"BWWBTTTTTTTBWWWWWWBTTTTTTTTTTTTT" +
		"BWBTTTTTTTTTBWWWWWWBTTTTTTTTTTTT" +
		"BBTTTTTTTTTTTBWWWWWWBTTTTTTTTTTT" +
		"BTTTTTTTTTTTTTBWWWWWWBTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTBBBBBBBBTTTTTTTTT";
/*
    private static final String ARROW_IMAGE_16x16 = {
        BBTTTTTTTTTTTTTT,
        BWBTTTTTTTTTTTTT,
        BWBTTTTTTTTTTTTT,
        BWWBTTTTTTTTTTTT,
        BWWBTTTTTTTTTTTT,
        BWWWBTTTTTTTTTTT,
        BWWWBTTTTTTTTTTT,
        BWWWWBTTTTTTTTTT,
        BWWWWBTTTTTTTTTT,
        BWWWBTTTTTTTTTTT,
        BWWBTTTTTTTTTTTT,
        BWWBTTTTTTTTTTTT,
        TBWWBTTTTTTTTTTT,
        TBWWBTTTTTTTTTTT,
        TTBWBTTTTTTTTTTT,
        TTBBTTTTTTTTTTTT,
    };
    
    private static final int[] ARROW_IMAGE_32x32 = {
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT,
        BTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT,
        BBTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT,
        BWBTTTTTTTTTTTTTTTTTTTTTTTTTTTTT,
        BWWBTTTTTTTTTTTTTTTTTTTTTTTTTTTT,
        BWWWBTTTTTTTTTTTTTTTTTTTTTTTTTTT,
        BWWWWBTTTTTTTTTTTTTTTTTTTTTTTTTT,
        BWWWWWBTTTTTTTTTTTTTTTTTTTTTTTTT,
        BWWWWWWBTTTTTTTTTTTTTTTTTTTTTTTT,
        BWWWWWWWBTTTTTTTTTTTTTTTTTTTTTTT,
        BWWWWWWWWBTTTTTTTTTTTTTTTTTTTTTT,
        BWWWWWWWWWBTTTTTTTTTTTTTTTTTTTTT,
        BWWWWWWWWWWBTTTTTTTTTTTTTTTTTTTT,
        BWWWWWWWWWWWBTTTTTTTTTTTTTTTTTTT,
        BWWWWWWWWWWWWBTTTTTTTTTTTTTTTTTT,
        BWWWWWWWWWWWWWBTTTTTTTTTTTTTTTTT,
        BWWWWWWWWWWWWWWBTTTTTTTTTTTTTTTT,
        BWWWWWWWWWWWWWWWBTTTTTTTTTTTTTTT,
        BWWWWWWWWBBBBBBBBBTTTTTTTTTTTTTT,
        BWWWWBWWWBTTTTTTTTTTTTTTTTTTTTTT,
        BWWWBTBWWWBTTTTTTTTTTTTTTTTTTTTT,
        BWWBTTBWWWBTTTTTTTTTTTTTTTTTTTTT,
        BWBTTTTBWWWBTTTTTTTTTTTTTTTTTTTT,
        BBTTTTTBWWWBTTTTTTTTTTTTTTTTTTTT,
        BTTTTTTTBWWWBTTTTTTTTTTTTTTTTTTT,
        TTTTTTTTBWWWBTTTTTTTTTTTTTTTTTTT,
        TTTTTTTTTBWWWBTTTTTTTTTTTTTTTTTT,
        TTTTTTTTTBWWWBTTTTTTTTTTTTTTTTTT,
        TTTTTTTTTTBWWWBTTTTTTTTTTTTTTTTT,
        TTTTTTTTTTBWWWBTTTTTTTTTTTTTTTTT,
        TTTTTTTTTTTBBBTTTTTTTTTTTTTTTTTT,
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT,
    };
*/
    private static final String RESIZE_VERTICAL_IMAGE_16x16 =
        "TTTTTTTTTTTTTTTT" +
        "TTTTTTTTTTTTTTTT" +
        "TTTTTTTTTTTTTTTT" +
        "TTTTTTTTTTTTTTTT" +
        "TTTBTTTTTTTTBTTT" +
        "TTBTTTTTTTTTTBTT" +
        "TBTTTTTTTTTTTTBT" +
        "BBBBBBBBBBBBBBBB" +
        "TBTTTTTTTTTTTTBT" +
        "TTBTTTTTTTTTTBTT" +
        "TTTBTTTTTTTTBTTT" +
        "TTTTTTTTTTTTTTTT" +
        "TTTTTTTTTTTTTTTT" +
        "TTTTTTTTTTTTTTTT" +
        "TTTTTTTTTTTTTTTT" +
        "TTTTTTTTTTTTTTTT"
    ;

    
    // --- Templates ---
    
	private static final String EMPTY_IMAGE_16x16 =
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT" +
	    "TTTTTTTTTTTTTTTT";

    private static final String EMPTY_IMAGE_32x32 =
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" +
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT";

    private static HardwareCursorImage ARROW_16x16 = new HardwareCursorImage(16, 16, ARROW_IMAGE_16x16, 0, 0);
    private static HardwareCursorImage ARROW_32x32 = new HardwareCursorImage(32, 32, ARROW_IMAGE_32x32, 0, 0);
    private static HardwareCursorImage RESIZE_VERTICAL_16x16 = new HardwareCursorImage(16, 16, RESIZE_VERTICAL_IMAGE_16x16, 0, 0);

    public static HardwareCursor ARROW = new HardwareCursor(new HardwareCursorImage[]{ARROW_16x16, ARROW_32x32});
    public static HardwareCursor RESIZE_VERTICAL = new HardwareCursor(new HardwareCursorImage[]{RESIZE_VERTICAL_16x16});
}
