/*
 * Automatically generated by jrpcgen 1.0.7 on 10/5/07 11:09 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.jnode.fs.nfs.nfs2.rpc.mount;

import java.io.IOException;

import org.acplt.oncrpc.OncRpcException;
import org.acplt.oncrpc.XdrAble;
import org.acplt.oncrpc.XdrDecodingStream;
import org.acplt.oncrpc.XdrEncodingStream;

public class FileHandle implements XdrAble {

    private byte[] value;

    public FileHandle() {
    }

    public FileHandle(byte[] value) {
        this.value = value;
    }

    public FileHandle(XdrDecodingStream xdr) throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) throws OncRpcException, IOException {
        xdr.xdrEncodeOpaque(value, Mount1Client.FILE_HANDLE_SIZE);
    }

    public void xdrDecode(XdrDecodingStream xdr) throws OncRpcException, IOException {
        value = xdr.xdrDecodeOpaque(Mount1Client.FILE_HANDLE_SIZE);
    }

    public byte[] getValue() {
        return value;
    }

}
// End of FileHandle.java
