/*
 * Automatically generated by jrpcgen 1.0.7 on 10/5/07 11:09 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.jnode.fs.nfs.nfs2.rpc.mount;

import java.io.IOException;

import org.acplt.oncrpc.OncRpcException;
import org.acplt.oncrpc.XdrAble;
import org.acplt.oncrpc.XdrDecodingStream;
import org.acplt.oncrpc.XdrEncodingStream;

public class MountResult implements XdrAble {
    private int status;
    private FileHandle directory;

    public MountResult() {
    }

    public MountResult(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        xdr.xdrEncodeInt(status);
        switch (status) {
            case 0:
                directory.xdrEncode(xdr);
                break;
            default:
                break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        status = xdr.xdrDecodeInt();
        switch (status) {
            case 0:
                directory = new FileHandle(xdr);
                break;
            default:
                break;
        }
    }

    public int getStatus() {
        return status;
    }

    public FileHandle getDirectory() {
        return directory;
    }


}
// End of MountResult.java
