/*
 * Automatically generated by jrpcgen 1.0.7 on 10/5/07 11:09 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.jnode.fs.nfs.nfs2.rpc.mount;

import java.io.IOException;

import org.acplt.oncrpc.OncRpcException;
import org.acplt.oncrpc.XdrAble;
import org.acplt.oncrpc.XdrDecodingStream;
import org.acplt.oncrpc.XdrEncodingStream;

public class Name implements XdrAble {

    private String value;


    public Name() {
    }

    public Name(String value) {
        this.value = value;
    }

    public Name(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        xdr.xdrEncodeString(value);
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        value = xdr.xdrDecodeString();
    }

    public String getValue() {
        return value;
    }


}
// End of Name.java
